### ISSUE TITLE
angulartr.com

### ISSUE THREAD

**Issue by gokaygurcan** [fatihacet/turkcekaynaklar-com#104]
Merhaba,

http://angulartr.com/ adresine ulaşılamıyor. Dolayısıyla tüm build'lere fail sonucu dönüyor Travis tarafıdan. 

@AlicanAkkus konuyla ilgili bir bilginiz var mı acaba? Yanlış görmediysem ekleyen sizsiniz.

**Comment by AlicanAkkus** [comment]
@gokaygurcan selam, bunu ben eklemedim diye görüyorum. 

benim repo üzerinde tek commitim var o da 6 Martta. Şuradan görebilrisin;
https://ibb.co/cGZfja

Not: Ekran görüntüsü 2 gün sonra otomatik silinecek.

**Comment by gokaygurcan** [comment]
Evet, şimdi tekrar baktım da iş biraz değişikmiş. 

Önceki seferde neden öyle bir izlenime kapılmışım bilmiyorum.

```bash
git log --no-merges -1 d860c6d0cf5325597a6422b2c0e19a015c494bd3

commit d860c6d0cf5325597a6422b2c0e19a015c494bd3
Author: Yasin Okumus <yasinokumus@gmail.com>
Date:   Thu Apr 13 14:52:54 2017 +0300

    angulartr.com
```

@lacivert gözüküyor author olarak. garip, kendime şaşırdım.

**Comment by lacivert** [comment]
Merhaba, pek hatirlamiyorum, eklemis olabilirim. Iyi bildigim bir site degil, ben de su anda erisemiyorum. Kaldirabiliriz
