### ISSUE TITLE
Code owners

### ISSUE THREAD

**Issue by gokaygurcan** [fatihacet/turkcekaynaklar-com#107]
Selamlar,

Geçen günlerde GitHub, Code Owners diye bir özellik duyurdu. Ayrıntılar için şuraya bakabiliriniz: https://github.com/blog/2392-introducing-code-owners

@fatihacet @lacivert ve kendimin olduğu bir `CODEOWNERS` dosyası yaratsam review olayını kolaylaştırmış olur muyuz dersiniz?

Cevaplarınız bekliyorum, teşekkürler.

**Comment by lacivert** [comment]
Deneyebiliriz bence

**Comment by fatihacet** [comment]
+1
