### ISSUE TITLE
bahattincinic.com

### ISSUE THREAD

**Issue by gokaygurcan** [fatihacet/turkcekaynaklar-com#109]
Selamlar,

bahattincinic.com'a girince "Alan adını yenilemek için lütfen kayıt firmasıyla bağlantı kurunuz." şeklinde bir uyarı çıkıyor. #108 build'i sırasında hata vermiş. 

@lacivert, ilgili kişiyi tanıyorsan siteyi tekrar aktif hale getirecek mi öğrenebilir miyiz? Ona göre bekleyelim ya da uçuralım.

https://github.com/fatihacet/turkcekaynaklar-com/commit/107826d014071b12753f07e85d5d8ee2afaa6788

**Comment by lacivert** [comment]
Kendisini sahsen tanimiyorum, sadece bir konusmasini dinlemistim. Yeni aklima gelen bu yaziyi paylastiktan kisa bir sure sonra boyle bir sey olmasi ilginc olmus. Twitter'dan kendisine yazayim, duruma gore karar verelim
