### ISSUE TITLE
Konu başlıklarını kategorilere bölme?

### ISSUE THREAD

**Issue by ekremkaraca** [fatihacet/turkcekaynaklar-com#139]
Herkese merhaba,

Konu başlıklarını kategorilere bölmenin daha yararlı ve böylece içeriğin daha anlaşılır olabileceği kanaatindeyim. Örneğin;

* Programlama dilleri
  * C
  * Java
  * Ruby
* Uygulama çatıları 
  * Codeigniter
  * Rails

ya da ;

* Front end web geliştirme
  * Angular
  * React
* Back end web geliştirme
  * Node.js
  * Java
* Mobil uygulama geliştirme
  * Android
  * React native

gibi?

**Comment by gokaygurcan** [comment]
Merhaba,

Fikir güzel fakat birden fazla kategoriye dahil olabilecek başlıklar için (mesela JavaScript) nasıl bir yol izlenebilir ya da bu daha mı çok kafa karıştırır düşünmek gerek. Hatta daha da önemlisi, #124 ile ilgili nasıl bir yol izlenecek ona karar verdikten sonra bu bölünme gerekli mi diye düşünmek gerek. 

/cc @fatihacet

**Comment by lacivert** [comment]
Merhaba, zaten daha once bu konu konusulmustu. 

Kisaca; 2. seviye maddeleme basitce mumkun degildi. 

Biraz da uzunca aciklamaya calisayim; Su anki bilgiler aslinda github uzerinden degil kendi alan adi olan turkcekaynaklar.com sitesi uzerinden, bir script araciligiyla derlenip toparlaniyor ☺️ ve yayimlaniyor. O bakimdan basit mantikla ikinci seviye maddeleme imkani konusunda bazi sorunlar vardi. @gokaygurcan hocamin bahsettigi gibi zaten sitenin altyapisi degisecek gibi, o zamana kadar da buna vakit ayirmak cok anlamli olmayabilir.

Tabi sitenin detaylari @fatihacet hocamda oldugu icin, onun belki diyecegi/yapabilecegi farkli seyler varsa bilemem 😄

**Comment by lacivert** [comment]
Onceki issue'lara bi gozattim ama bir ustteki yorumumda yazdigim seyi goremedim, baska bir mesele ile karistirmis da olabilirm. Kusura bakmayin 😄

**Comment by fatihacet** [comment]
@lacivert sikinti tam olarak oyle degildi abi. Projenin sitesi olan TurkceKaynaklar.com bizim bu repoda yer alan README.md kullanilarak generate ediliyor. README.md'deki icerigi kategorilere ayirdigimiz zaman sitedeki icerik icin ekstra isler yapmamiz gerekiyordu.

Benim siteyi basit bir icerik sitesinden ziyade bir platforma donusturme fikrim var. #124 Bir haftasonu 5-6 saat ayirabilirsem biraz ilerlerim diye dusunuyorum. Onu yaptigimiz zaman buna gerek kalmayacaktir diye dusunuyorum.

@ekremkaraca fikrin icin tesekkurler 👍
