### ISSUE TITLE
@baransomakli

### ISSUE THREAD

**Issue by gokaygurcan** [fatihacet/turkcekaynaklar-com#142]
Merhaba @baransomakli,

Link'lerden 3 tanesinde Twitter handle'ınız kullanılmış, fakat Twitter'dan "baransomakli" için 404 dönüyor. Bilinçli şekilde yapılmışsa, son halini öğrenme şansımız var mıdır? Ona göre gerekli düzenlemeleri yapalım ya da tamamen kaldıralım. 

Teşekkürler,
G.

**Comment by baransomakli** [comment]
Merhaba @gokaygurcan 

Dün twitter hesabimi geçici olarak dondurduğum için 404 vermiş olmalı şuan aktif bir şekilde duruyor.

**Comment by gokaygurcan** [comment]
Kelebek etkisi işte. Sen -herhangi bir sebepten- bir hesabını kapatıyorsun, tamamen alakasız bir yerde, tamamen alakasız bir projenin testleri hata vermeye başlıyor. Hayat çok garip.
