### ISSUE TITLE
Slack Grupları

### ISSUE THREAD

**Issue by MrPeker** [fatihacet/turkcekaynaklar-com#149]
Slack Grupları kısmına Prototürk ve Anladım Hocam eklenebilir

**Comment by fatihacet** [comment]
@MrPeker ekle abi o zaman.

**Comment by MrPeker** [comment]
onu tayfun erbilen ile mustafa zahid efe ye demek lazım :D

**Comment by gokaygurcan** [comment]
Anlaşılmadı. 
Eğer başkalarına faydalı olacağını düşünüyorsanız ekleyin listeye. Burada oluşturulan içerik için kimse sadece kendine ait site/proje/kanal gibi şeyleri eklemedi, o yüzden gelip de o iki kişinin ekleme yapmasını beklemek çok anlamsız olur.
