### ISSUE TITLE
Laravel Istanbul Slack kayıt sayfası eksikliği

### ISSUE THREAD

**Issue by bilalbaraz** [fatihacet/turkcekaynaklar-com#177]
Sadece **login link** verilmiş. Diğer gruplarda olduğu gibi **kayıt** linki eklenmeliydi. Kayıt olamadım.
@euma3us eklemiş sanırım (commitlerden gördüğüm kadarıyla)

**Comment by lacivert** [comment]
Bence de problemli bir durum. Sanirim diger link sorunlari sirasinda arada kaynadi ( #171 )

Bu arada diger PR'da bir de davetiye linki var; buradaki sorunun cozumu degil ama calisiyosa sizin icin ise yarayabilir; https://github.com/euma3us/turkcekaynaklar-com/blob/3696f9649c63b6a76dd06cd5d00cdaa56d728ef5/README.md

**Comment by bilalbaraz** [comment]
@lacivert link işe yaradı. teşekkürler.

**Comment by euma3us** [comment]
Durumdan ötürü özürlerimi sunuyorum, o an canlı davetiye linkine ulaşamamıştım. Şimdi @bilalbaraz 'ın zamanında doğrusunu koyduğu ve şimdilerde ölü olan davetiye linkini güncellemek için bi' pull request açtım. bilginize

**Comment by gokaygurcan** [comment]
Süper! Bu Slack davetiyeleri meselesini bir şekilde çözmek gerek, süreki sorun çıkartacak gibiler :)
