### ISSUE TITLE
www.batuhansaka.com

### ISSUE THREAD

**Issue by gokaygurcan** [fatihacet/turkcekaynaklar-com#192]
/ping @strawb3rryx7

Merhaba,
Sanırım websitenizi yayından kaldırıp Medium'a yönlendirme yapmışsınız. Burada bulunan URL'ler için bir çalışma yapacak mısınız? Yönlendirme falan gibi mesela. Eğer yapmayacaksanız PR'ları bekletmemek adına listeden silineceklerinin bilgisini vermiş olalım. 

Sevgiler,
G.

**Comment by strawb3rryx7** [comment]
Selamlar,

İlgili URL’de bir adet anlatım bulunmaktaydı. Bu hafta içerisinde ilgili
anlatım ile ilgili Medium üzerinde bir yazı hazırlayarak PR göndererek
durumu çözeceğim.

Bilgilerinize.

**Comment by fatihacet** [comment]
Sorun giderilmis gozukuyor. Tesekkurler @strawb3rryx7 @gokaygurcan 👍
