### ISSUE TITLE
yusufcakmak.com

### ISSUE THREAD

**Issue by gokaygurcan** [fatihacet/turkcekaynaklar-com#197]
/ping @yusufcakmak

Merhaba,
Java kategorisi altında geçen [Java ve kütüphanelerini içeren blog](http://yusufcakmak.com/category/java/) adresi artık ulaşılamaz durumda gözüküyor. Yakın zamanda geri gelmeyecekse bu kaynağın silineceğini haber vermek isterim. 

Sevgiler,
G.

**Comment by yusufcakmak** [comment]
Merhaba,

@gokaygurcan evet o kategoriye ait içerikler tekrar dönmeyecek. Silebilirsen sevinirim.

haber verdiğin için de çok teşekkür ederim :)

**Comment by gokaygurcan** [comment]
Teşekkürler.
