### ISSUE TITLE
tekil yazılar dahil edilsin mi?

### ISSUE THREAD

**Issue by lacivert** [fatihacet/turkcekaynaklar-com#21]
Bir blog içinde sadece belli bir konuya özel Türkçe kaynak olmayabilir. Hatta bazen koca sitede bir tane ama güzel bir kaynak olarak tek yazı oluyor, bu tip yazılar da burada paylaşılmalı mı? (Bence evet) Bunun için de ayrı bir sayfa ya da kategori gibi bir şey yapılması güzel olur. Ya da nasıl bir organizasyon daha iyi olur?

**Comment by fatihacet** [comment]
Bence de dahil edilmeli. Sonucta onlar da onemli Turkce icerikler. Bence direk konu basliginin altina suan yaptigimiz gibi ekleyebiliriz. Ne diyorsun?

**Comment by gokaygurcan** [comment]
Link kurbağa olursa zaten tespit etmek kolay, o yüzden ne kadar kaynak varsa buraya yığılması taraftarıyım.

**Comment by fatihacet** [comment]
Mantikli. O zaman tekil linkleri ilgili kategoriler altina ekliyip devam ediyoruz. Bu issue'yu kapatiyorum. Tesekkurler @lacivert @gokaygurcan 👍
