### ISSUE TITLE
Bağlantılar için küçük resimler eklenebilir mi?

### ISSUE THREAD

**Issue by zafer06** [fatihacet/turkcekaynaklar-com#211]
Öncelikle büyük bir emek harcayarak tüm bunları gerçekleştiren arkadaşlara teşekkür etmek isterim.

Siteyi gördüm ve basitliğini sevdim. Video bağlantılarının yanında video simgesi var. Bunun gibi örneğin makale ve diğer farklı bağlantılar için de küçük simgeler eklenebilir mi?

Ben denemek isterdim ama kaynak kodları göremedim!

**Comment by fatihacet** [comment]
@zafer06 selamlar 👋 

Kaynak kod [GitLab'de](gitlab.com/fatihacet/turkcekaynaklar-com) tutuluyor, cunku deploy GitLab tarafinda GitLab Pages'la yapiliyor.

Icerik olarak bir tane [README.md](https://github.com/fatihacet/turkcekaynaklar-com/blob/master/README.md) dosyamiz var, eger onu degistirirsen GitLab'de deploy trigger olacak.

Ilerleyen zamanlarda siteyi sadece basit bir liste olmaktan ziyade daha kapsamli bir hale donusturmeyi dusunuyoruz. [Su](https://github.com/fatihacet/turkcekaynaklar-com/issues/124) issue'ya bakabilirsin.

**Comment by zafer06** [comment]
Selamlar @fatihacet,

Sanırım kaynak kod bağlantı adresi yanlış olmuş. 

Anladığım kadarıyla sitenin veri deposu olarak README.md dosyasını kullanıyorsunuz. Ancak ruby ve jekyll konusunda hiç tecrübem olmadığı için projeyi incelemek oldukça zor oldu :)

"Sadelik, mükemmelliğe giden yoldur." derler, görünen o ki güzel işler yapıyorsunuz. Umarım böyle devam eder.

**Comment by lacivert** [comment]
@zafer06, dogru baglanti adresini bulmussun sanirim ama yine de yorumdaki baglanti adresini degistirdim

http://gitlab.com/fatihacet/turkcekaynaklar-com
