### ISSUE TITLE
Linkedin linkleri testten geçmiyor

### ISSUE THREAD

**Issue by muratdogan17** [fatihacet/turkcekaynaklar-com#212]
Kendime task olsun diye açıyorum ancak bakmak isteyen olursa yok demem :)

**Comment by lacivert** [comment]
Ilgili olabilir; https://stackoverflow.com/questions/30288642/http-error-999-request-denied

**Comment by gokaygurcan** [comment]
https://github.com/dkhamsing/awesome_bot/issues/165

bakalım neler olacak.

**Comment by gokaygurcan** [comment]
Görünüşe göre şu an için whitelist ya da başka bir URL kullanmak dışında bir seçeneğimiz yok. Öğrenmiş olduk.

**Comment by fatihacet** [comment]
O zaman Linkedin linkleri kabul etmeyelim derim. 

Case closed 😀
