### ISSUE TITLE
Kirik baglantilar

### ISSUE THREAD

**Issue by lacivert** [fatihacet/turkcekaynaklar-com#220]
@MertcanGokgoz , @rizagunes sitelerinizdeki bazi baglantilar calismiyor, bunlar hakkindaki planlariniz neler? Yenilenmeyecekse kaldirilsin mi?

  1. [L297] 404 https://mertcangokgoz.com/tag/nginx/  
  2. [L334] 500 http://www.rizagunes.com/kategori/php  
  3. [L476] 404 https://mertcangokgoz.com/tag/jekyll/

**Comment by rizagunes** [comment]
@lacivert yakın zamanda sunucu değişikliği yaptım benim de haberim yoktu. Teşekkür ettim :)

**Comment by gokaygurcan** [comment]
Görünüşe göre 3 link de geri döndü. Travis'in şu anki haline aldırmayın, merge butonuna basmadan önce tekrar çalıştırmam gerekiyordu, unuttum.

**Comment by lacivert** [comment]
Tesekkurler
