### ISSUE TITLE
yakutrb.com

### ISSUE THREAD

**Issue by gokaygurcan** [fatihacet/turkcekaynaklar-com#223]
Merhaba @tgezginis,

Yeterince geriye gidince yakutrb.com'un şu commit'te eklendiğini gördüm: https://github.com/fatihacet/turkcekaynaklar-com/commit/66862f0437c1f3c8527fef8427f13c1e045d27e7

Görünüşe göre domain artık aktif değil (exp date: 2018-04-04). Bu domain'le bir alakanız var mı yoksa doğrudan @sdogruyol ile mi iletişime geçelim? 

Sevgiler,
G.

**Comment by tgezginis** [comment]
Selam Gökay,

@enderahmetyurt daha iyi bilgi verebilir.

Sevgiler.

**Comment by enderahmetyurt** [comment]
Merhaba @gokaygurcan evet @sdogruyol'da domain. Ben kendisi ile konuşabilirim. Teşekkürler.

**Comment by sdogruyol** [comment]
Merhabalar! Domain'in kaydı bende fakat süresi geçti. Ay sonu tekrar yenileyeceğim :+1:
