### ISSUE TITLE
kulekci.net baglantisi calismiyor

### ISSUE THREAD

**Issue by lacivert** [fatihacet/turkcekaynaklar-com#286]
ping @aredhelrim & @hkulekci 

"Usulüne Uygun PHP" baglantisi calismiyor. Geri donmeyecekse kaldirabilir miyiz?

**Comment by hkulekci** [comment]
Kontrol edelim. Bende yeni farkettim.

**Comment by hkulekci** [comment]
@aredhelrim @lacivert domain süresi dolmuş. Şu anda çalışıyor.

**Comment by hkulekci** [comment]
Buraya ayrıca teknoloji ekleyebiliyor muyuz? Şuralarda türkçe birşeyler karalamıştım ekleyebiliriz aslında.

https://medium.com/@kulekci
https://elasticsearch.kulekci.net/

**Comment by lacivert** [comment]
Tesekkurler, 
https://github.com/fatihacet/turkcekaynaklar-com/blob/master/Katki-Cagrisi.md
