### ISSUE TITLE
Katkıda bulunmak istedim

### ISSUE THREAD

**Issue by ksckaan** [fatihacet/turkcekaynaklar-com#291]
Aslında bir sorunum yok. Golang hakkında kendi yazmış olduğum Türkçe PDF ile katkıda bulunmak istiyorum. Buyrun linki:
https://github.com/ksckaan/golangtrpdf

**Comment by fatihacet** [comment]
Bunun icin README.md dosyasini degistirip Pull Request acabilirsin.

**Comment by gokaygurcan** [comment]
https://github.com/fatihacet/turkcekaynaklar-com/blob/master/.github/CONTRIBUTING.md

şunu şöyle bırakalım, belki faydası olur.
