### ISSUE TITLE
Linkler doğru çalışmıyor

### ISSUE THREAD

**Issue by ahmetcadirci25** [fatihacet/turkcekaynaklar-com#308]
Swift kategorisi altındaki linklerde sorun var.

**Comment by gokaygurcan** [comment]
Merhaba,
Swift kategorisi altında 43 tane link var. Hangisinden ya da hangilerinden bahsediyoruz acaba?

**Comment by ahmetcadirci25** [comment]
https://www.turkcekaynaklar.com

Sayfayı açıp, swift kategorisine bakarsanız hatayı görebilirsiniz.

**Comment by gokaygurcan** [comment]
@fatihacet & @lacivert , 
Görünüşe göre aradaki | (pipe) sembolleri link'lerin olduğudan farklı anlaşılmasına ve tabloya dönüştürülmesine sebep oluyor. Aklımızda olsun.

@ahmetcadirci25,
Issue için teşekkürler, ilerde daha açıklayıcı olmaya çalışırsanız harika olur. "X çalışmıyor" şeklinde açılan bir issue hiçkimsenin işini kolaylaştırmıyor.

**Comment by lacivert** [comment]
👍 tesekkurler
