### ISSUE TITLE
WordPress Başlığı

### ISSUE THREAD

**Issue by fikret** [fatihacet/turkcekaynaklar-com#338]
WordPress başlığı altındaki "WordPress Tema Entegre Eğitim Seti - Baran Somaklı" maddesindeki Youtube videosu silinmiş.
WordPress konusunda hata çözümleri, çeşitli verimlilik artıracak yazılar içinse şurayı tavsiye ederim:
https://wpokulu.co/nasil-yapilir/
Teşekkürler.

**Comment by lacivert** [comment]
Tesekkurler, calismayan linkleri silip istediginiz linkleri de ekleyerek PR acabilirsiniz
