### ISSUE TITLE
Python Yazbel Linki Bozuk

### ISSUE THREAD

**Issue by EkremDincel** [fatihacet/turkcekaynaklar-com#340]
Yazbel sitesi geçen günlerde taşındı ve bazı URL adresleri değiştirildi. "Python" bölümündeki "Python Dersleri - İstihza, Yazbel" bağlantısının yeni linki https://python-istihza.yazbel.com/ olmalı.

**Comment by lacivert** [comment]
Tesekkurler, musait oldugumuzda bakabiliriz ya da isterseniz siz de ilgili degisikligi yapaak PR gonderebilirsiniz

**Comment by melihs** [comment]
"Blockchain Altyapısı Teknik Bilgiler" adlı içeriği gösteren web sitesi (http://blockchainturk.net/) sitesi kapanmış. Eğer site başka bir yere taşınmışsa @mehmetcemyucel güncel url ' i ekleyebilir ya da listeden kaldırılabilir

**Comment by mehmetcemyucel** [comment]
Kaldirabiliriz, tesekkurler.

**Comment by EkremDincel** [comment]
https://github.com/fatihacet/turkcekaynaklar-com/pull/352
