### ISSUE TITLE
Kirik link: jargon.ist

### ISSUE THREAD

**Issue by lacivert** [fatihacet/turkcekaynaklar-com#374]
@ahmetcadirci25 Jargon.ist sitesi geri gelecek mi?

**Comment by ahmetcadirci25** [comment]
@lacivert sitenin sahibi değilim. bunun cevabını repo sahipleri cevap verebilir.

https://github.com/orgs/jargonist/people

@alpcanaydin @burakcan @fatihacet @hsnaydd

**Comment by gokaygurcan** [comment]
aa iyi projeydi, uzucu oldu. 

/ping @alpcanaydin

**Comment by gokaygurcan** [comment]
Belli ki gelmeyecek.
