### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by myygunduz** [fatihacet/turkcekaynaklar-com#442]
Pull requests isteklerine bakıyor musunuz?

**Comment by gokaygurcan** [comment]
Vakit buldukça. Fatih de ben de tatildeyiz, o yüzden çok da düzenli bakılıyor demek güç. 

Sorun neydi? Ona göre yardım etmeye çalışalım.

**Comment by myygunduz** [comment]
16 tane pull request görünce merak ettimde

**Comment by gokaygurcan** [comment]
Son birkaç hafta içinde açılanlar haricindekiler açan kişilerden bir şeyler bekliyor. Kalanlar da dediğim gibi, tatil nedeniyle bekliyor.
