### ISSUE TITLE
Bu konuya destek adına bir platform

### ISSUE THREAD

**Issue by alibuyukkilinc** [fatihacet/turkcekaynaklar-com#476]
Çalışmayı yakinen takip ediyorum, koddan ziyade bazen öyle yerlerde takılıyoruz ki araştıra araştıra çözüyoruz ve bazen tekrar karşılaşıyoruz aynı problemle veya başka biri aynı sorunu yaşıyor ama bizim kadar yetenekli değil diyelim. Nacizane Türkçe kaynağa ve çözüme destek, yeni yetişen genç arkadaşlarımızın neyi nasıl araştıracağını bilmeyen ingilizce yeterliliği az veya aradığı sorunu Türkçe de bulmasına imkan tanıyan bir platform kurdum. Eğer destek olursanız hep birlikte büyüyebilir ben elimden geldiğince yazmaya çalışacağım. Link  www.mycodelibs.com

**Comment by gokaygurcan** [comment]
https://github.com/fatihacet/turkcekaynaklar-com/blob/master/Katki-Cagrisi.md
