### ISSUE TITLE
Auto deploy mekanizmasi

### ISSUE THREAD

**Issue by fatihacet** [fatihacet/turkcekaynaklar-com#55]
@gokaygurcan @lacivert Bildiginiz uzere repo GitHub'da ama turkcekaynaklar.com GitLab Pages ile serve ediliyor. Nedeniyse markdown content generate edebilmek icin ozel bir helper kullaniyorum ve GitHub onu desteklemedi. Bende cok fazla ugrasmayip uzaktancalismak.com'da yaptigim gibi GitLab Pages'dan sunmaya basladim.

GitHub'a Pull Request merge edince turkcekaynaklar.com otomatik olarak guncellenmiyordu, ben elle gidip content'i update ediyordum. Biraz once GitHub'dan merge edince GitLab'a bir bos commit yapacak bir hook yazdim ve GitLab'de statik siteyi build ederken son icerigi GitHub'dan cekecek bir gulp script yazdim. Sozun kisasi, suan GitHub'dan bir PR merge ederseniz, turkcekaynaklar.com'da 3-4 dk icinde gozukmesi gerekiyor.

Haberiniz olsun.

**Comment by fatihacet** [comment]
@gokaygurcan @lacivert ^^

**Comment by gokaygurcan** [comment]
Süp-per, eline sağlık.

Normalde sadece kontrol yapıp, approve/change gerekirse onu belirtip merge işini sana bırakıyordum; fakat 2 x ✅ alanı içeri alırım bundan sonra. Sanırım aynısı @lacivert için de geçerli :) 

Liste güzel ilerliyor bu arada, içerikler de oldukça eğlenceli.
