### ISSUE TITLE
Frameworkler nasil gruplanmali 

### ISSUE THREAD

**Issue by aredhelrim** [fatihacet/turkcekaynaklar-com#57]
Dillere ait bir cok framework olabiliyor. Ornegin PHP icin 

Codeigniter, Symfony, Laravel vb. bunlarin her birini main section olarak kabul etmek mi mantikli yoksa PHP Frameworkler gibi bi section altinda gruplamak mi daha dogru olur ?

**Comment by lacivert** [comment]
Ben alt grup olması fikrini daha çok benimsiyorum ama çok da fark etmez, sonuçta `Ctrl+F` ile iş çözülüyor 😄

**Comment by aredhelrim** [comment]
Dogru aslinda :)

**Comment by fatihacet** [comment]
`Cmd+F` ile is cozuluyor ama alt grup insanlarin konu listesine bakarken "aa bununla da ilgili icerik varmis" demesini saglar. Sonuc olarak Alt grup listelerine 👍 diyorum ama var olan icerigi guncellemeli miyiz ondan emin degilim. Simdilik oldugu gibi mi gitsek?

**Comment by lacivert** [comment]
Herkesin kabul edebileceği şeyleri bu hale getirelim bence; 

- PHP
  - Laravel
  - CodeIgniter

- Javascript
  - jQuery
  - VueJS
  - React

gibi

**Comment by fatihacet** [comment]
@lacivert 👍 

Birinin bunlari oturup gruplamasi lazim 😞

**Comment by lacivert** [comment]
gruplamaya biraz baktım ama markdown ile tam nasıl daha güzel olur/görünür, bilemiyorum. Üst başlıklar iyi de alt taraflar karışıyor. Örnek olması açısından bir PR gönderiyorum birazdan

**Comment by lacivert** [comment]
Bir de Android, Java altında mı olmalı? 😄
