### ISSUE TITLE
Siteye Emoji destegi eklemek

### ISSUE THREAD

**Issue by fatihacet** [fatihacet/turkcekaynaklar-com#58]
![http://f.acet.me/nRnX.png](http://f.acet.me/nRnX.png)

En basit cozum olarak kullancagimiz emoji'leri regex ile image olarak replace edebiliriz.

**Comment by lacivert** [comment]
Fikir üretirken sitedeki görüntü aklıma gelmemişti. Kolayca çözülüyorsa güzel.

**Comment by fatihacet** [comment]
Gulpfile'da emojileri destekleyecek bir degisiklik yaptim. Kod degisikligi [surada](https://gitlab.com/fatihacet/turkcekaynaklar-com/commit/74dadd3838ea72a0ac72d95f799acdc93beeec9c#ee9d2cf188170ffae6c24450b921d4dd26b8dfaf). 

Suan sadece `:movie_camera:` emojisini base64 png image olarak replace ediyor. Eger bir baska emoji kullanacaksak onu da Gulpfile'a elle eklemek gerekiyor. En basit ve hizli cozum buydu. 

![http://f.acet.me/VXGY.png](http://f.acet.me/VXGY.png)

@lacivert @gokaygurcan Pull Request'leri merge ederken `:movie_camera:` disinda emoji kullanimi varsa lutfen merge etmeyin. Ya GitLab'daki repo'ya da Merge Request acin ya da beni ping'leyin ben hallederim.

**Comment by gokaygurcan** [comment]
Harika çözüm olmuş, uyarı için teşekkürler ^_^
