### ISSUE TITLE
nasıl katkı sağlayabilirim

### ISSUE THREAD

**Issue by dbyilmaz** [fatihacet/turkcekaynaklar-com#69]
Merhabalar ben katkı sağlamak istiyorum nasıl yapabilirim .

**Comment by lacivert** [comment]
Listede bulunmayan Türkçe kaynakları tavsiye edebilirsiniz.

**Comment by dbyilmaz** [comment]
Hocam ben fork ettikten sonra commit ettim doğru mu yaptım bu sisteme tam olarak daha alışamadım :)

**Comment by gokaygurcan** [comment]
@dbyilmaz, istersen şurdan başla: https://try.github.io/

Genel hatlarıyla anlatıyor neyin ne olduğunu ve nasıl yapılacağını.

**Comment by lacivert** [comment]
@dbyilmaz , biraz reponuza baktım, kendi reponuza değişiklikleri göndermişsiniz (push). Şimdi ilgili değişiklikleri bu repoya değişiklik isteği yani Pull Request (PR) yapmanız gerekiyor. Kendi reponuzdan "New pull request" butonuna tıklayarak bu repoya PR gönderebilirsiniz.

**Comment by dbyilmaz** [comment]
@gokaygurcan  teşekkür ederim. 
@lacivert PR yolladım hocam teşekkür ederim.

**Comment by lacivert** [comment]
İşlem anlaşıldığına göre kapatıyorum
