### ISSUE TITLE
Youtube linklerinde feed URL'leri tüm aktiviteyi gösteriyor

### ISSUE THREAD

**Issue by lacivert** [fatihacet/turkcekaynaklar-com#77]
Bunun sonucunda da bir kişinin Youtube kanalının /feed sayfasına link vermişsek ve bu kişi de alakasız bir videoyu beğendiyse (like) o da bu akışta görünüyor, bu bakımdan bence /feed URL'leri kullanılmamalı diye düşünüyorum. Siz ne dersiniz?

**Comment by gokaygurcan** [comment]
Daha sayfa yüklenirken Videos tab'ine geçen biri olarak fark etmediğim durum ama muhtemelen probleme dönüşebilecek bir şey. 
Süper fikir! Home ya da feed yerine Videos link'i verilirse sorun çözülecektir.

**Comment by lacivert** [comment]
Aynen, bence de Videos tabındaki link daha uygun olacaktır diye düşünüyorum

**Comment by fatihacet** [comment]
Bu yuzden benim butun like ettigim videolar private. Begendigim videolar diye ayri bir playlist var, eger bir videonun benim kanalimda gozukmesini istiyorsam onu begendigim videolar playlist'ine kendim elle ekliyorum. Ama kanallarin %92'sinde bu public oldugu icin kirlilik olacaktir, dogru bir nokta @lacivert 👍 

O zaman bundan sonra YT linki eklerken bunu da goz onunde bulunduralim. Bu issue'yu kapatiyorum, sanirim almamiz gereken aksiyonu aldik. Eger yapilmasi gereken ya da konusulmasi gereken baska konu varsa issue'yu tekrar aciniz efendim. 

@lacivert @gokaygurcan ikinize de cok tesekkur ediyorum 😍

**Comment by lacivert** [comment]
Bu arada madem Contributing file'i da yapiliyor, bu noktayi da oraya ekleyebiliriz diye dusunuyorum. Boylece daha belirgin olmus olur.
