### ISSUE TITLE
İstihza Hakkında

### ISSUE THREAD

**Issue by aligoren** [fatihacet/turkcekaynaklar-com#89]
Selamlar Fırat Özgül tarafından yayında olan istihza artık kapalı. Onun yerine istihza kendisi şu adresleri öneriyor:

https://github.com/yazbel/python-istihza

https://belgeler.yazbel.com/python-istihza/

**Comment by gokaygurcan** [comment]
Merhaba,
Bir sonraki Travis build'i link'in kurbağa olduğunu fark edecekti ama doğrusunu öğrenmek süper oldu!

Lütfen README'yi olması gerektiği şekilde günceller misiniz? 

Teşekkürler!

**Comment by aligoren** [comment]
@gokaygurcan PR açtım. Teşekkürler

**Comment by lacivert** [comment]
teşekkürler
