### ISSUE TITLE
Javascript'te Promise link'i ölmüş

### ISSUE THREAD

**Issue by abdurrahmanekr** [fatihacet/turkcekaynaklar-com#96]
www.eksiduyuru.com' domain altında bulunuyor siteye de girilmiyor.  http://www.eksiduyuru.com/duyuru/947270/javascript-te-promise

**Comment by lacivert** [comment]
Anlık bir hata olmasın? Ben şu anda görebiliyorum, herhangi bir sorun yok.

**Comment by abdurrahmanekr** [comment]
Hmm dün giremiyordum. Bugün düzeltilmiş kapatayım o zaman.
